In [18]:
import pandas as pd

In [19]:
dataset=pd.read_csv('insurance_pre.csv')

In [20]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [21]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [22]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [23]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [24]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [25]:
dependent=dataset[['charges']]

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'splitter':['best','random'],'max_features':['auto','sqrt','log2']}
grid = GridSearchCV(DecisionTreeRegressor(),param_grid,refit= True, verbose = 3, n_jobs= -1)

grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.71340064 0.66091423 0.68880164 0.67513721
        nan        nan 0.69471135 0.63735142 0.66597997 0.66912176
        nan        nan 0.68330944 0.64406921 0.68966083 0.67830453
        nan        nan 0.69792281 0.64771989 0.66236742 0.63574934]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [29]:
result=grid.cv_results_
print("The R_score value for best prameter {}".format(grid.best_params_))

The R_score value for best prameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'}

In [30]:
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002611,0.000606,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.001806,0.000165,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.009110,0.001156,0.004574,0.000295,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.738155,0.632758,0.752224,0.688853,0.755012,0.713401,0.046813,1
3,0.008637,0.001360,0.004373,0.000291,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.663685,0.545911,0.655973,0.660155,0.778847,0.660914,0.073711,12
4,0.009491,0.001970,0.004314,0.000347,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.651558,0.606632,0.772238,0.709452,0.704128,0.688802,0.056146,5
5,0.008121,0.000940,0.004544,0.000188,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.668490,0.559022,0.729139,0.695001,0.724033,0.675137,0.062014,8
6,0.001988,0.000569,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001651,0.000338,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.009448,0.000682,0.004237,0.000373,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.731761,0.667919,0.764663,0.688238,0.620976,0.694711,0.049925,3
9,0.007706,0.000491,0.005894,0.001501,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.655872,0.492424,0.691631,0.689437,0.657392,0.637351,0.074038,15
10,0.008767,0.000475,0.004537,0.000935,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.721184,0.635926,0.718303,0.541320,0.713167,0.665980,0.069936,10
11,0.007575,0.000375,0.004701,0.000645,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.709731,0.634457,0.713638,0.633376,0.654406,0.669122,0.035572,9
12,0.001701,0.000249,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001745,0.000349,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.028008,0.002167,0.003933,0.000510,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.767925,0.586259,0.572434,0.687146,0.802784,0.683309,0.092909,6
15,0.019620,0.001402,0.003917,0.000426,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.732524,0.610755,0.466648,0.694949,0.715471,0.644069,0.098081,14
16,0.027529,0.001700,0.004387,0.000866,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.665187,0.619574,0.769984,0.680052,0.713506,0.689661,0.050247,4
17,0.020058,0.001094,0.003954,0.000593,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.680320,0.583875,0.705119,0.694895,0.727314,0.678305,0.049633,7
18,0.001843,0.001104,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001527,0.000314,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.008850,0.000537,0.004740,0.000932,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.763063,0.592073,0.714221,0.728095,0.692162,0.697923,0.057718,2
21,0.007857,0.000843,0.004088,0.000444,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.666795,0.594720,0.644841,0.723825,0.608418,0.647720,0.045864,13
22,0.009527,0.001086,0.003793,0.000420,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.648111,0.657605,0.749692,0.598300,0.658130,0.662367,0.048937,11
23,0.007765,0.000591,0.004173,0.000396,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.717232,0.613105,0.645330,0.656661,0.546419,0.635749,0.055966,16

In [31]:
age=float(input("Age: "))     
bmi=float(input("BMI: "))
children=int(input("Children: "))
sex_Male=int(input("Sex Male 0 or 1: "))
smoker_yes=int(input("Smoker Yes 0 or 1: "))

Age:  43
BMI:  34
Children:  3
Sex Male 0 or 1:  1
Smoker Yes 0 or 1:  0

In [32]:
Future_Prediction= grid.predict([[age,bmi,children,sex_Male,smoker_yes]])
print("Future Prediction={}".format(Future_Prediction))

Future Prediction=[9563.029]

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(