In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent= dataset[['charges']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [9]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [12]:
#applying standarisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
# preprocessing output
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [13]:
x_train

array([[-0.14853305,  0.54530479,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.59867181, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.96092064,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.91339361, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.77656186, -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97749955, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [14]:
y_train

array([[ 2.25338687],
       [-1.00752925],
       [ 2.11386131],
       ...,
       [-0.65022604],
       [-0.96502226],
       [-0.70448219]], shape=(1070, 1))

In [15]:

from sklearn.svm import SVR 
# regressor=SVR(kernel='sigmoid',C=10000)
#using non linear poly
regressor=SVR(kernel='poly')
regressor.fit(x_train,y_train)

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(kernel='poly')

In [29]:
# regressor.coef_

In [16]:
y_pred=regressor.predict(x_test)
y_pred

array([-2.36860268e-01, -3.27997917e-01,  2.86183181e+00, -3.62909382e-02,
       -1.16767022e-01, -6.46891952e-01, -1.01899055e+00, -9.82653749e-02,
       -4.19127778e-01, -5.82336059e-01, -4.48626119e-01, -2.30350071e-01,
       -4.07577796e-01, -6.27482301e-01,  1.04214175e+00, -1.72708503e-01,
       -8.88407971e-02, -7.50866454e-01, -4.89505032e-01,  1.09356979e+00,
        1.03371269e+00, -3.63799030e-02, -2.52592589e-01,  1.39767650e+00,
       -8.76885171e-01, -6.19714178e-01, -5.79714694e-01, -3.66303848e-01,
       -6.83745860e-01, -3.36998591e-01, -3.84005506e-01,  3.30680986e+00,
       -5.57113987e-03, -2.15847370e-01,  5.68941186e-04, -7.12862566e-01,
       -3.11892288e-01,  2.00752902e+00,  1.97136261e+00, -9.19268581e-01,
       -4.74606105e-01, -7.88745311e-01,  1.07976951e+00,  2.76706828e+00,
        1.83921723e+00, -8.02681773e-01, -1.74217855e-01, -4.62125030e-01,
       -6.41665086e-01, -1.13339375e-01, -8.37028186e-01, -8.46789667e-01,
        1.44585603e+00,  2.67664734e+00, -1.54407858e-02, -7.54389495e-01,
       -7.88558387e-01, -3.49474012e-01, -2.42250947e-01, -2.14108550e-02,
       -1.00776541e+00,  2.08034078e+00,  1.47260816e-01, -2.14803381e-01,
       -1.66863110e-01, -1.81477750e-01,  9.99086456e-01,  1.80181152e+00,
       -8.43852900e-01, -3.57649143e-01, -5.16708180e-02, -1.12386889e-01,
        6.40560209e-01,  1.05997547e-01, -7.23619259e-02, -7.93983255e-02,
       -3.94649528e-01, -3.58456403e-01,  9.60900767e-01,  2.82557235e+00,
       -1.70753826e-01,  3.38541484e+00, -8.97032841e-01, -3.96106044e-01,
        2.22771192e+00,  7.73793268e-01, -7.26990002e-01, -8.28028066e-01,
       -5.74032769e-02,  1.98416890e+00, -5.22572498e-01, -2.36225741e-01,
       -7.78108870e-01, -3.31805604e-01, -6.55978196e-01, -6.20036150e-01,
        1.99775381e+00,  1.63003147e+00, -5.91739618e-01, -1.92778932e-01,
       -8.71690204e-01, -5.60373894e-01, -6.50975688e-01,  2.04490687e+00,
        1.33474885e+00, -7.28102383e-01, -1.61068880e-01, -7.30109365e-01,
       -1.38886254e-01,  2.40045997e+00, -7.64933173e-02, -6.89319929e-01,
       -3.08844218e-01,  1.15362583e+00,  3.33776955e+00, -4.09757518e-01,
       -9.71977497e-01, -3.50379321e-01, -2.09892711e-02, -2.66996222e-01,
        2.24960509e+00, -1.09119338e-01,  1.76583710e-01, -5.87745881e-01,
       -3.91824740e-01, -6.14753949e-01,  1.15984704e+00,  6.69645034e-01,
        3.29160740e+00, -8.61744331e-01, -3.45544596e-01, -8.89733280e-01,
       -5.04157867e-01, -2.84840005e-01,  1.62970219e+00,  1.54167703e+00,
        9.02958596e-01, -2.22450369e-01,  7.45840056e-01, -8.65100388e-01,
       -9.31210817e-01, -2.36054938e-01, -2.37687632e-01, -2.53723627e-01,
       -6.29397306e-01,  1.26722046e-01,  2.54498437e-02, -7.96904662e-01,
       -1.05064171e+00, -1.86198252e-01, -5.10244483e-01,  2.57496495e+00,
       -2.54707934e-01, -9.47493904e-01, -8.50878266e-01, -4.67596839e-01,
       -8.41742053e-01, -9.57697770e-01, -1.72898668e-01, -2.08621860e-01,
       -6.51854587e-01, -2.13564997e-03, -8.07281628e-02, -2.54194717e-01,
       -5.83266613e-01, -6.87252111e-01, -1.19606460e-02, -5.60191551e-01,
       -6.91710338e-01, -9.21164104e-01, -6.79878781e-01, -7.09203328e-01,
       -3.62000274e-01, -8.19257625e-01, -6.68914914e-01, -6.67360910e-01,
       -7.19803682e-01, -4.96155165e-01,  1.87164840e+00, -1.06321821e+00,
       -1.57728308e-01, -4.60683369e-01, -1.70396726e-01, -7.85494506e-01,
       -5.75625032e-01,  1.56417568e+00, -9.01702846e-01, -8.90374869e-01,
        8.21214817e-02, -2.16300228e-01,  2.04519176e+00, -7.11821967e-01,
       -5.47165188e-01,  9.88711651e-01, -8.04065744e-01, -9.10638827e-01,
       -5.07632107e-01, -5.01862271e-01, -6.27646482e-01, -6.84071148e-01,
       -1.53402848e-01,  2.64908156e+00, -7.34579100e-02,  7.83164865e-01,
       -6.53165110e-01,  2.53837975e+00, -7.89724248e-01, -2.98702257e-01,
       -5.00767979e-01, -8.88925194e-01, -3.24565775e-01,  6.54449946e-03,
       -6.39698173e-01, -8.47624269e-01, -4.82469862e-01, -9.12837614e-01,
       -4.94153424e-01, -5.76664803e-01,  4.74541701e-02, -3.60803456e-01,
       -4.85394692e-01, -3.99738893e-01, -3.44887495e-01, -8.10160910e-01,
       -8.85942329e-02,  6.53766394e-02, -4.59970387e-03, -1.24541444e-01,
       -4.34090658e-01, -8.86694106e-01, -1.01168355e+00, -3.69523236e-01,
       -3.79431578e-02, -7.98301780e-01, -6.16674422e-01, -4.17322671e-01,
       -3.11439341e-01,  1.28246933e+00, -5.44961044e-01, -1.61603427e-01,
       -5.44406489e-01,  1.62066606e+00, -3.77256960e-01, -4.30132259e-01,
       -3.32298677e-01, -2.09179413e-01, -8.82958723e-01, -3.85008986e-01,
       -8.89736235e-01, -4.73004666e-01,  1.20369263e+00,  2.21940691e+00,
       -6.85080647e-01, -7.43223990e-01, -1.00597267e+00, -1.08218031e+00,
       -3.85841350e-01, -9.36789883e-01, -7.16356031e-01, -7.28093798e-01,
       -2.54144728e-01,  1.39573751e+00,  2.33843271e+00,  9.52078289e-02,
       -4.83164172e-01, -1.63527209e-01,  2.46573290e+00, -2.65147667e-01])

In [17]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8755183188209155

In [20]:
import pickle
#save input standard scalar
pickle.dump(sc,open("input_scalar.pkl",'wb'))
#save the model    
pickle.dump(regressor,open("final_model.pkl",'wb'))
#Save output standard scalar
pickle.dump(scy,open("output_scalar.pkl",'wb'))

In [26]:
preinput=sc.transform([[40,38,2,1,0]])

In [27]:
pre_output=scy.inverse_transform([regressor.predict(preinput)])

In [28]:
pre_output

array([[1448.77373562]])