In [19]:
import pandas as pd

In [20]:
dataset=pd.read_csv('insurance_pre.csv')

In [21]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [22]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [23]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [24]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [25]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent= dataset[['charges']]

In [26]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [27]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [30]:
x_train

      age     bmi  children  sex_male  smoker_yes
621    37  34.100         4      True        True
194    18  34.430         0      True       False
240    23  36.670         2     False        True
1168   32  35.200         2      True       False
1192   58  32.395         1     False       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[1070 rows x 5 columns]

In [31]:
#applying standarisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [32]:
x_train

array([[-0.14853305,  0.54530479,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.59867181, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.96092064,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.91339361, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.77656186, -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97749955, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [33]:

from sklearn.svm import SVR 
regressor=SVR(kernel='sigmoid',C=10000)
#using non linear poly
# regressor=SVR(kernel='poly')
regressor.fit(x_train,y_train)

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=10000, kernel='sigmoid')

In [29]:
# regressor.coef_

In [34]:
regressor.n_support_

array([1070], dtype=int32)

In [35]:
regressor.intercept_

array([4674.20623784])

In [36]:
y_pred=regressor.predict(x_test)
y_pred

array([  11411.27366006,   14522.40625739, -132555.59531022,
        144994.97473826,  -93679.69693317,  -79144.70917232,
        132399.84268536,  152446.08046964,   25687.54369312,
         49462.71613588, -105510.23897101,   18992.07026183,
         19403.52163273,   75426.07384479,  121449.99917635,
         86925.9920657 ,  138795.47037305,  -42526.33756767,
        -16314.38569653,  142591.73141545,   -4223.02258295,
         98652.44855117,  -34229.28917249,   13634.80193529,
        -84362.58378084,    8653.78386478,   37707.68221156,
         54311.3840987 ,   87553.4257399 ,  -39682.31377991,
         29447.15626845, -133167.93661979,  142226.26434557,
        118296.25897245,  118859.84192378,   84212.37631581,
        -51319.57296474,  122648.2961768 ,  -43669.76485806,
         43947.73772515,   23895.67016821,  -99425.91335583,
         96496.16878054, -225270.94183184,   49116.47167244,
        -69526.95575119,   83303.94185077,   -3421.46792414,
         13170.57409904,  -41441.41299699,   14266.06776485,
       -105129.26557504,   25864.27283381,   10646.88292428,
         -9512.0636456 ,  -31667.99851293,  -41666.73938668,
         63141.46475526,  171913.91498898,   87796.25311942,
       -154484.84443872, -242146.88555337, -133436.07194487,
        -63670.7460923 ,  -84506.19301491,   36713.11754791,
        143470.97264602,   55107.69793201,  -65356.33257612,
         44831.18924677,  -77567.76798031,   43667.48940686,
        129248.40718   ,  -35336.51247112,  -94953.913683  ,
        -76490.66895519,   28570.72167296,  -39341.8703547 ,
         19492.112407  , -140060.88004483,  -54121.84794028,
       -103975.6303583 , -105660.24192214,   -8931.66303431,
         -5585.63910653,  109975.42395401,  -76048.26650983,
        -95490.26275164,   54337.36958235,  104988.79260086,
         -2029.51513935,   97180.90394719,  -76978.8339266 ,
         22170.59584525,   -9995.2317488 ,   15862.30094247,
         20994.23424276,  -27810.79764799,  -21243.86175358,
        147783.83191184,  -95294.29680479,  -21976.08404094,
        -37059.83804034,   76062.12227371,  -11815.97270517,
         92919.30848575,  112127.34545892,    9254.35982918,
        117908.57091261,  -13961.23585237,   14448.73523687,
         94650.74211777,   11712.20322906,  150495.96592585,
       -115334.02031872,    8494.35085647,  -99862.92704033,
         63095.79692498,   18086.90541293,   36416.45956945,
       -115325.99371325,  -96340.66977109,  -13363.13438169,
         39787.65963954,   13584.13815336,  -74244.97835993,
         -4164.9814445 ,   58424.39781629,  -49331.17743817,
        -40860.10880646,   31545.79410797,  -38326.56966133,
         21029.68202441,   71823.82542589,   70439.27599008,
         97114.15757217,   96924.65520774,  -11925.62858319,
        -35467.86266362,  -74415.58530264,   66532.742322  ,
         99316.47069878,  -66037.94050652,   93183.37281143,
        -35017.06097515,  -40954.43459698,   46684.00916872,
        -54457.60705222, -189961.98896981,   53644.11987401,
         23931.67169496,  125009.62865162,     582.42300475,
        -72109.79508456,  -87932.0412988 ,   21866.44479271,
        -56255.4424637 ,  -76635.30521639,   86492.30685944,
        112068.38184319,   67375.0293685 ,  158851.56503756,
        -84848.32328641,   35224.7411245 ,   56211.28785059,
        164631.76767726,  148326.7817518 ,  -23792.45193308,
        -48853.13019198,  -65056.25509451,    3727.26718654,
          7799.33443473,   31821.80092165,  -44270.30587954,
         77709.84618953,  155659.30496579,   19803.91260259,
         -1485.380785  , -201560.97127885, -177243.24594761,
         70653.14388276,   12459.34150109,  111162.00854048,
        -60932.64179081,   31349.00165306,   50966.01124464,
       -110056.79561407,   41498.83402589,  -60321.17676404,
         67465.44864806,   26850.74095507,  -36806.64529756,
         24264.08608099,   90166.43783591,  -43310.24690201,
       -143584.90295657,  -18224.77897246,    5106.86882589,
         16384.09382503,  -48269.47583675,   20291.05271734,
        -33299.23658725,   88119.98106971,  124265.01237037,
         -4026.34545361,  -27945.27728364,   11684.41304598,
         86667.44870194,   -4491.46564059,   61367.36720838,
         -6012.21207642,  -63663.99667565,  -61658.71347245,
         38452.05353868,  -16977.13732372, -152433.11979817,
         54220.42490666,    7260.54034572,  128078.69108176,
       -109861.73221645,   17129.14175769,  -30043.08441885,
        -14048.99196123,  113672.93494143,  -49532.62075354,
        150272.72586727,  119287.38021508,  -78113.54113006,
        113959.62096482, -137231.26314752, -146206.41664354,
         32815.54660311,  -43633.46420173,  -98181.7265602 ,
         21892.09966898,  -41402.84489938,    5169.80675396,
        132304.65253157,  -25152.80505009,   -5149.15816384,
         45163.57493271,  186072.29660967,   32704.67961636,
         14236.69509905,  -15855.17962107,    9353.50381729,
          8453.13248374,   12693.94407201,  124645.3396712 ,
          2414.07579953,   37921.97850208,   16636.88044723,
        -52010.12699744,  -79717.65943091,  107663.64605928,
       -191601.29889877,  -10656.5304236 ,  -16962.17144606,
        204789.0924796 ,   29428.7151494 ,  114620.71007091,
         -7884.33486805,  -10538.72999037,   88194.80089982,
        -15746.83783364,  150168.64245344, -102926.495389  ,
         51780.65903349])

In [37]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

-42.538913988043724