In [25]:
import pandas as pd

In [26]:
dataset=pd.read_csv('insurance_pre.csv')

In [27]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [28]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [29]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [30]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [31]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent= dataset[['charges']]

In [32]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [33]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [35]:
x_train

      age     bmi  children  sex_male  smoker_yes
621    37  34.100         4      True        True
194    18  34.430         0      True       False
240    23  36.670         2     False        True
1168   32  35.200         2      True       False
1192   58  32.395         1     False       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[1070 rows x 5 columns]

In [36]:
#applying standarisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [37]:
x_train

array([[-0.14853305,  0.54530479,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.59867181, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.96092064,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.91339361, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.77656186, -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97749955, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [38]:

from sklearn.ensemble import AdaBoostRegressor
regressor=AdaBoostRegressor()
regressor.fit(x_train,y_train)

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor()

In [29]:
# regressor.coef_

In [19]:
# regressor.n_support_

In [22]:
# regressor.intercept_

In [39]:
y_pred=regressor.predict(x_test)
y_pred

array([14783.20945339, 13024.05827422, 47997.77955682, 14953.95845545,
       11472.01189773,  7182.6755643 ,  7182.6755643 , 13024.05827422,
       10814.49212946,  7182.6755643 ,  7182.6755643 , 13024.05827422,
       10814.49212946,  7182.6755643 , 19867.63717179, 13024.05827422,
       15235.74885652,  7182.6755643 , 10814.49212946, 39515.23892916,
       25538.97567977, 17845.66118164, 13846.84668843, 25538.97567977,
        7182.6755643 ,  7182.6755643 ,  7182.6755643 , 10814.49212946,
        7182.6755643 , 11472.01189773, 10814.49212946, 47997.77955682,
       15235.74885652, 13846.84668843, 19867.63717179,  7182.6755643 ,
       11472.01189773, 39515.23892916, 42116.65758063,  7182.6755643 ,
        7182.6755643 ,  7182.6755643 , 19867.63717179, 47997.77955682,
       39515.23892916,  7182.6755643 , 13024.05827422, 10814.49212946,
        7182.6755643 , 14783.20945339,  7182.6755643 ,  7182.6755643 ,
       25538.97567977, 47997.77955682, 11472.01189773,  7182.6755643 ,
        7182.6755643 , 11472.01189773, 10814.49212946, 15235.74885652,
        7182.6755643 , 47997.77955682, 17845.66118164, 13024.05827422,
       13024.05827422, 11472.01189773, 39515.23892916, 42116.65758063,
        7182.6755643 , 10814.49212946, 15235.74885652, 14783.20945339,
       18006.66256935, 15235.74885652, 15235.74885652, 15235.74885652,
       11472.01189773, 10814.49212946, 19867.63717179, 47997.77955682,
       13846.84668843, 42116.65758063,  7182.6755643 , 11472.01189773,
       42116.65758063, 19867.63717179,  7182.6755643 ,  7182.6755643 ,
       15235.74885652, 39515.23892916,  7182.6755643 , 13846.84668843,
        7182.6755643 , 11472.01189773,  7182.6755643 ,  7182.6755643 ,
       47997.77955682, 39515.23892916,  7182.6755643 , 11472.01189773,
        7182.6755643 ,  7182.6755643 ,  7182.6755643 , 42116.65758063,
       25538.97567977,  7182.6755643 , 13846.84668843,  7182.6755643 ,
       13846.84668843, 47997.77955682, 17845.66118164,  7182.6755643 ,
       13024.05827422, 39515.23892916, 47997.77955682, 10814.49212946,
        7182.6755643 , 11472.01189773, 15235.74885652, 11472.01189773,
       42116.65758063, 13846.84668843, 14953.95845545,  7182.6755643 ,
       10814.49212946,  7182.6755643 , 25538.97567977, 25538.97567977,
       47997.77955682,  7182.6755643 , 10814.49212946,  7182.6755643 ,
       10814.49212946, 11472.01189773, 25538.97567977, 42116.65758063,
       25538.97567977, 13024.05827422, 25538.97567977,  7182.6755643 ,
        7182.6755643 , 13846.84668843, 13024.05827422, 13846.84668843,
        7182.6755643 , 15235.74885652, 15235.74885652,  7182.6755643 ,
        7182.6755643 , 14783.20945339, 10814.49212946, 39515.23892916,
       13024.05827422,  7182.6755643 ,  7182.6755643 , 10814.49212946,
        7182.6755643 ,  7182.6755643 , 13024.05827422, 13024.05827422,
        7182.6755643 , 14953.95845545, 15235.74885652, 11472.01189773,
        7182.6755643 ,  7182.6755643 , 18006.66256935,  7182.6755643 ,
        7182.6755643 ,  7182.6755643 ,  7182.6755643 ,  7182.6755643 ,
       10814.49212946,  7182.6755643 ,  7182.6755643 ,  7182.6755643 ,
        7182.6755643 , 10814.49212946, 25538.97567977,  7182.6755643 ,
       17845.66118164, 10814.49212946, 13846.84668843,  7182.6755643 ,
        7182.6755643 , 25538.97567977,  7182.6755643 ,  7182.6755643 ,
       15235.74885652, 13024.05827422, 47997.77955682,  7182.6755643 ,
        7182.6755643 , 25538.97567977,  7182.6755643 ,  7182.6755643 ,
       10814.49212946,  7182.6755643 ,  7182.6755643 ,  7182.6755643 ,
       14783.20945339, 47997.77955682, 17845.66118164, 19867.63717179,
        7182.6755643 , 47997.77955682,  7182.6755643 , 13846.84668843,
        7182.6755643 ,  7182.6755643 , 13024.05827422, 15235.74885652,
        7182.6755643 ,  7182.6755643 , 10814.49212946,  7182.6755643 ,
        7182.6755643 ,  7182.6755643 , 17845.66118164, 10814.49212946,
        7182.6755643 , 10814.49212946, 11472.01189773,  7182.6755643 ,
       13846.84668843, 14953.95845545, 17845.66118164, 13846.84668843,
       10814.49212946,  7182.6755643 ,  7182.6755643 , 11472.01189773,
       15235.74885652,  7182.6755643 ,  7182.6755643 , 10814.49212946,
       13024.05827422, 39515.23892916, 10814.49212946, 17845.66118164,
        7220.02535   , 39515.23892916, 10814.49212946,  7220.02535   ,
       10814.49212946, 14783.20945339,  7182.6755643 , 10814.49212946,
        7182.6755643 , 10814.49212946, 19867.63717179, 47997.77955682,
        7182.6755643 ,  7182.6755643 ,  7182.6755643 ,  7182.6755643 ,
       11472.01189773,  7182.6755643 ,  7182.6755643 ,  7182.6755643 ,
       11472.01189773, 25538.97567977, 47997.77955682, 17845.66118164,
       10814.49212946, 11472.01189773, 39515.23892916, 11472.01189773])

In [40]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8640780358883042