In [7]:
import pandas as pd

In [8]:
dataset=pd.read_csv('insurance_pre.csv')

In [9]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [10]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [11]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [12]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [13]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent= dataset[['charges']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [9]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [11]:
x_train

      age     bmi  children  sex_male  smoker_yes
621    37  34.100         4      True        True
194    18  34.430         0      True       False
240    23  36.670         2     False        True
1168   32  35.200         2      True       False
1192   58  32.395         1     False       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[1070 rows x 5 columns]

In [15]:
#applying standarisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
x_train

array([[-0.14853305,  0.54530479,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.59867181, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.96092064,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.91339361, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.77656186, -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97749955, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [16]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\acer\anaconda\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\acer\anaconda\lib\site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in c:\users\acer\anaconda\lib\site-packages (from lightgbm) (1.16.3)

In [17]:
import lightgbm as lgb
regressor=lgb.LGBMRegressor()
regressor.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000070 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 316
[LightGBM] [Info] Number of data points in the train set: 1070, number of used features: 5
[LightGBM] [Info] Start training from score 13201.182046

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LGBMRegressor()

In [29]:
# regressor.coef_

In [34]:
regressor.n_support_

array([1070], dtype=int32)

In [35]:
regressor.intercept_

array([4674.20623784])

In [18]:
y_pred=regressor.predict(x_test)
y_pred

C:\Users\ACER\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

array([10625.70224663,  9529.45011367, 43570.55330856, 12116.95062332,
        9565.09487557,  7163.856269  ,  1356.57095935, 10919.88970684,
        8466.90419693,  3302.43132301,  7404.8083356 , 14226.52694558,
        9144.11991822,  6623.07966815, 21995.20066062, 12056.38168344,
       13777.50995495,  5381.30437052,  6604.94669251, 35354.17671108,
       24790.48557155, 14247.50948824, 11021.28386893, 27035.80391814,
        5476.21370935,  5478.55501851,  5220.33918977,  6230.06498245,
        2638.0244467 , 11457.38236254,  7338.55675906, 48504.48441601,
       17619.5334994 , 11984.99236828, 17346.66439236,  4077.63903404,
       11725.99704105, 36978.61888252, 39092.20492298,  3171.6969347 ,
        5617.76698612,  4878.5161989 , 19673.4445374 , 48364.57682998,
       35939.31432376,  5941.58618701, 12212.32118903,  6953.06617532,
        5260.07031115, 12013.43847224,  1635.17507118,  6817.28495286,
       26501.47832265, 43975.11188144, 12260.55113376,  7608.59616449,
        6025.78557705, 11302.70718381,  8728.18690983, 16936.66151839,
        1735.70709064, 46151.115672  , 16611.24098989, 14972.87394088,
       13916.33655848,  7090.65417555, 34373.52645009, 38810.56361655,
        5765.94945239,  8534.27005737, 15631.74384915, 10831.6855    ,
       18351.31314429, 16573.58597189, 14682.69919783, 16069.23346184,
        9162.72193313, 12013.66277239, 18780.68457352, 47804.67703153,
        9847.52027632, 48236.52272474,  2550.14208423, 11266.32884691,
       40521.0625688 , 19427.15685243,  4588.59892623,  2729.7047895 ,
       14693.85205117, 39197.22764218,  3840.45236081, 14219.21392981,
        2511.40348959, 10634.63724777,  5436.74763178,  3356.00834292,
       45322.24976548, 41331.69537953,  4986.86699355, 10508.15229064,
        5063.06762297,  9215.18479781,  9286.08774369, 38933.07173674,
       29165.92126703,  3464.42001427, 10021.79363594,  1630.54249149,
       13575.39772286, 45843.77278291, 11464.4074033 ,  3412.12839329,
        8752.74702996, 33318.74871184, 49904.58018536,  7171.20622305,
        1979.05953907, 10752.85185283, 21569.09831304,  8233.40064313,
       40990.31627041, 11899.60480477, 13129.85393989,  5068.3180449 ,
       11545.43646196,  6291.09001903, 25264.60273926, 26070.80009695,
       48892.46054212,  1160.96136959, 13330.94765282,  6517.07058683,
        7941.3819463 ,  8727.50500407, 40649.302842  , 38344.43384155,
       23929.66261121, 11856.45774987, 23874.40305327,  9013.43467062,
        2410.16997941, 14545.63127693, 15496.19514342, 11874.26096458,
        4707.83145229, 13446.18762297, 18737.58296738,  9935.62702022,
        2002.16796036, 12202.76791681,  7282.42353743, 40689.49893377,
        9545.9357329 ,  4164.70273569,  4855.17284024,  8379.85073923,
        1876.19470242,  3386.11606293, 12056.38168344,  9886.1760632 ,
        6650.53185198, 13006.50725179, 13902.07558247,  6631.6256413 ,
        4259.99015297,  6858.00810717, 15337.52112283,  7542.61910767,
        6096.68321491,  2043.25134209,  9683.99817139,  9540.86580325,
       11738.26883202,  2741.1081028 ,  7353.0829293 ,  7235.09145792,
        6165.13631208,  7207.92579036, 27975.85509941,  1764.34572465,
       16782.15632487,  5765.17851562,  9965.21395291,  6064.73264866,
        6903.28053888, 27554.35888177,  2373.11216922,  3721.06930879,
       12502.99937431, 12143.96038841, 42459.8843784 ,  8240.69929498,
        4859.61617584, 23693.87895797,  2752.76875466,  5430.58746572,
        9166.84197149,  5857.43540691,  4814.83284416,  4590.03134296,
       14379.98577535, 46921.62554397, 15334.89318887, 19289.99320665,
        6526.62506793, 43170.93440004,  4274.25983277,  9986.88513432,
        8113.6209871 ,  2274.20804147,  9499.26344406, 13475.57650512,
        7844.68807931,  3595.66739981,  6469.85546785,  5701.46556555,
        6747.44837403,  6455.2211555 , 13773.48628633,  7845.53523213,
        8883.29342655,  7575.58271263,  9702.78742171,  4187.97671782,
       13263.28305554, 14245.1103071 , 21766.59891293, 13284.98744244,
        5771.89230316,  1555.00185221,  3319.36286918,  7776.52668667,
       15457.36407337,  7131.74296768,  6014.49207248,  6155.56660493,
       14736.31316583, 34905.29411657,  4909.27920864, 12140.85486782,
        7750.54806287, 37544.60324856,  7883.36052418,  7742.67463764,
        9530.89947092, 11960.72070586,  5470.84029469,  8309.79069972,
        4739.64401385,  6796.97185937, 20666.48267631, 46043.52342362,
        4683.92561086,  4588.59892623,  1861.16391251,  2495.27628213,
        9318.15814181,  1536.90869326,  4817.58606156,  9438.70141988,
        7804.66352613, 25291.33078775, 45447.16610309, 16452.41510149,
        7079.72272413, 10600.19647559, 43629.82045584,  8410.67264539])

In [19]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8825932367755079