In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent= dataset[['charges']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [9]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=0)

In [11]:
x_train

      age     bmi  children  sex_male  smoker_yes
621    37  34.100         4      True        True
194    18  34.430         0      True       False
240    23  36.670         2     False        True
1168   32  35.200         2      True       False
1192   58  32.395         1     False       False
...   ...     ...       ...       ...         ...
763    27  26.030         0      True       False
835    42  35.970         2      True       False
1216   40  25.080         0      True       False
559    19  35.530         0      True       False
684    33  18.500         1     False       False

[1070 rows x 5 columns]

In [15]:
#applying standarisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
x_train

array([[-0.14853305,  0.54530479,  2.41394802,  1.01506676,  1.97125461],
       [-1.49780784,  0.59867181, -0.89219519,  1.01506676, -0.50729114],
       [-1.14273553,  0.96092064,  0.76087642, -0.98515688,  1.97125461],
       ...,
       [ 0.06451033, -0.91339361, -0.89219519,  1.01506676, -0.50729114],
       [-1.42679338,  0.77656186, -0.89219519,  1.01506676, -0.50729114],
       [-0.4325909 , -1.97749955, -0.06565939, -0.98515688, -0.50729114]],
      shape=(1070, 5))

In [16]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\acer\anaconda\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\acer\anaconda\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 1.6/101.7 MB 9.8 MB/s eta 0:00:11
   - -------------------------------------- 3.4/101.7 MB 10.6 MB/s eta 0:00:10
   -- ------------------------------------- 5.5/101.7 MB 10.5 MB/s eta 0:00:10
   -- ------------------------------------- 6.8/101.7 MB 9.3 MB/s eta 0:00:11
   -- ------------------------------------- 7.3/101.7 MB 7.9 MB/s eta 0:00:12
   --- ------------------------------------ 7.9/101.7 MB 6.6 MB/s eta 0:00:15
   --- ------------------------------------ 8.4/101.7 MB 5.9 MB/s eta 0:00:16
   --- ------------------------------------ 8.9/101.7 MB 5.4 MB/s eta 0:00:18
   --- ------------------------------------ 9.4/101.7 MB 5.1 MB/s eta 0:00:18
   --- ------------------------------------ 10.0/101.7 MB 4.9 MB/s eta 0:00:19
   ---- ----------------------------------- 10.5/101.7 MB 4.7 MB/s eta 0:00:20
   ---- ----------------------------------- 11.3/101.7 MB 4.6 MB/s eta 0:00:20
   ---- ----------------------------------- 11.8/101.7 MB 4.5 MB/s eta 0:00:20
   ---- ----------------------------------- 12.6/101.7 MB 4.4 MB/s eta 0:00:21
   ----- ---------------------------------- 13.4/101.7 MB 4.4 MB/s eta 0:00:21
   ----- ---------------------------------- 14.2/101.7 MB 4.4 MB/s eta 0:00:21
   ----- ---------------------------------- 15.2/101.7 MB 4.3 MB/s eta 0:00:20
   ------ --------------------------------- 16.0/101.7 MB 4.3 MB/s eta 0:00:20
   ------ --------------------------------- 17.0/101.7 MB 4.4 MB/s eta 0:00:20
   ------- -------------------------------- 17.8/101.7 MB 4.4 MB/s eta 0:00:20
   ------- -------------------------------- 18.9/101.7 MB 4.4 MB/s eta 0:00:19
   ------- -------------------------------- 19.9/101.7 MB 4.5 MB/s eta 0:00:19
   -------- ------------------------------- 21.2/101.7 MB 4.5 MB/s eta 0:00:18
   -------- ------------------------------- 22.3/101.7 MB 4.5 MB/s eta 0:00:18
   --------- ------------------------------ 23.6/101.7 MB 4.6 MB/s eta 0:00:17
   --------- ------------------------------ 24.6/101.7 MB 4.6 MB/s eta 0:00:17
   ---------- ----------------------------- 26.0/101.7 MB 4.7 MB/s eta 0:00:17
   ---------- ----------------------------- 27.0/101.7 MB 4.7 MB/s eta 0:00:16
   ----------- ---------------------------- 28.3/101.7 MB 4.8 MB/s eta 0:00:16
   ----------- ---------------------------- 29.6/101.7 MB 4.8 MB/s eta 0:00:15
   ------------ --------------------------- 30.9/101.7 MB 4.9 MB/s eta 0:00:15
   ------------ --------------------------- 32.2/101.7 MB 4.9 MB/s eta 0:00:15
   ------------- -------------------------- 33.8/101.7 MB 5.0 MB/s eta 0:00:14
   ------------- -------------------------- 35.4/101.7 MB 5.1 MB/s eta 0:00:14
   -------------- ------------------------- 37.0/101.7 MB 5.2 MB/s eta 0:00:13
   --------------- ------------------------ 38.5/101.7 MB 5.2 MB/s eta 0:00:13
   --------------- ------------------------ 39.8/101.7 MB 5.2 MB/s eta 0:00:12
   --------------- ------------------------ 40.6/101.7 MB 5.2 MB/s eta 0:00:12
   ---------------- ----------------------- 41.4/101.7 MB 5.2 MB/s eta 0:00:12
   ---------------- ----------------------- 42.5/101.7 MB 5.2 MB/s eta 0:00:12
   ----------------- ---------------------- 43.3/101.7 MB 5.2 MB/s eta 0:00:12
   ----------------- ---------------------- 44.6/101.7 MB 5.2 MB/s eta 0:00:12
   ----------------- ---------------------- 45.6/101.7 MB 5.2 MB/s eta 0:00:11
   ------------------ --------------------- 46.7/101.7 MB 5.2 MB/s eta 0:00:11
   ------------------ --------------------- 48.0/101.7 MB 5.2 MB/s eta 0:00:11
   ------------------- -------------------- 49.3/101.7 MB 5.2 MB/s eta 0:00:11
   ------------------- -------------------- 50.6/101.7 MB 5.3 MB/s eta 0:00:10
   -------------------- ------------------- 51.9/101.7 MB 5.3 MB/s eta 0:00:10
   -------------------- ------------------- 53.2/101.7 MB 5.3 MB/s eta 0:00:10
   --------------------- ------------------ 54.5/101.7 MB 5.3 MB/s eta 0:00:09
   ---------------------- ----------------- 56.1/101.7 MB 5.4 MB/s eta 0:00:09
   ---------------------- ----------------- 57.4/101.7 MB 5.4 MB/s eta 0:00:09
   ----------------------- ---------------- 59.0/101.7 MB 5.4 MB/s eta 0:00:08
   ----------------------- ---------------- 60.3/101.7 MB 5.4 MB/s eta 0:00:08
   ------------------------ --------------- 61.9/101.7 MB 5.5 MB/s eta 0:00:08
   ------------------------ --------------- 63.4/101.7 MB 5.5 MB/s eta 0:00:07
   ------------------------- -------------- 64.7/101.7 MB 5.5 MB/s eta 0:00:07
   -------------------------- ------------- 66.3/101.7 MB 5.6 MB/s eta 0:00:07
   -------------------------- ------------- 67.6/101.7 MB 5.6 MB/s eta 0:00:07
   --------------------------- ------------ 68.7/101.7 MB 5.6 MB/s eta 0:00:06
   --------------------------- ------------ 69.5/101.7 MB 5.6 MB/s eta 0:00:06
   --------------------------- ------------ 70.5/101.7 MB 5.5 MB/s eta 0:00:06
   ---------------------------- ----------- 71.6/101.7 MB 5.5 MB/s eta 0:00:06
   ---------------------------- ----------- 72.6/101.7 MB 5.5 MB/s eta 0:00:06
   ---------------------------- ----------- 73.7/101.7 MB 5.5 MB/s eta 0:00:06
   ----------------------------- ---------- 75.0/101.7 MB 5.5 MB/s eta 0:00:05
   ----------------------------- ---------- 76.0/101.7 MB 5.5 MB/s eta 0:00:05
   ------------------------------ --------- 77.3/101.7 MB 5.5 MB/s eta 0:00:05
   ------------------------------ --------- 78.4/101.7 MB 5.5 MB/s eta 0:00:05
   ------------------------------- -------- 79.7/101.7 MB 5.5 MB/s eta 0:00:04
   ------------------------------- -------- 80.7/101.7 MB 5.5 MB/s eta 0:00:04
   -------------------------------- ------- 82.1/101.7 MB 5.6 MB/s eta 0:00:04
   -------------------------------- ------- 83.4/101.7 MB 5.6 MB/s eta 0:00:04
   --------------------------------- ------ 84.7/101.7 MB 5.6 MB/s eta 0:00:04
   --------------------------------- ------ 86.2/101.7 MB 5.6 MB/s eta 0:00:03
   ---------------------------------- ----- 87.6/101.7 MB 5.6 MB/s eta 0:00:03
   ----------------------------------- ---- 89.1/101.7 MB 5.6 MB/s eta 0:00:03
   ----------------------------------- ---- 90.4/101.7 MB 5.6 MB/s eta 0:00:02
   ------------------------------------ --- 92.0/101.7 MB 5.7 MB/s eta 0:00:02
   ------------------------------------ --- 93.6/101.7 MB 5.7 MB/s eta 0:00:02
   ------------------------------------- -- 94.9/101.7 MB 5.7 MB/s eta 0:00:02
   -------------------------------------- - 96.7/101.7 MB 5.7 MB/s eta 0:00:01
   -------------------------------------- - 98.0/101.7 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  99.4/101.7 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  100.7/101.7 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 5.6 MB/s  0:00:18
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [19]:
import xgboost as xgb
regressor=xgb.XGBRegressor(n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    objective='reg:squarederror')
regressor.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [29]:
# regressor.coef_

In [34]:
regressor.n_support_

array([1070], dtype=int32)

In [35]:
regressor.intercept_

array([4674.20623784])

In [20]:
y_pred=regressor.predict(x_test)
y_pred

array([11740.009 ,  9826.652 , 44846.344 , 11869.501 ,  9738.008 ,
        5883.1455,  2298.828 , 11353.319 ,  7406.293 ,  5749.6406,
        6784.927 , 15265.659 ,  9242.721 ,  6413.5044, 25512.781 ,
       11613.546 , 13450.76  ,  5765.7197,  6659.272 , 34800.37  ,
       23841.693 , 14925.687 , 11174.948 , 28261.67  ,  3379.9817,
        4677.0103,  7355.773 ,  7670.2554,  3428.204 , 10010.83  ,
        7229.6562, 47945.79  , 16750.96  , 12642.58  , 16673.918 ,
        3973.402 ,  9214.44  , 37405.46  , 38915.836 ,  3333.9033,
        6805.461 ,  4021.0554, 18812.879 , 47174.727 , 38065.387 ,
        5107.051 , 11719.327 ,  6552.9683,  5368.601 , 12189.577 ,
        3314.3806,  6796.671 , 26336.367 , 45228.91  , 10726.9795,
        7067.641 ,  6525.488 , 10540.78  ,  9480.359 , 15651.539 ,
        2190.867 , 45251.426 , 16305.548 , 15392.362 , 11503.515 ,
        9880.193 , 36724.2   , 39986.297 ,  4927.112 , 12485.007 ,
       14806.829 , 12070.919 , 18276.62  , 15604.272 , 13629.425 ,
       14065.865 ,  9294.07  , 10029.1455, 19305.998 , 47981.703 ,
       11333.987 , 50424.33  ,  2847.7783,  9315.903 , 39518.49  ,
       19192.148 ,  4236.6724,  4152.2295, 15496.797 , 38901.164 ,
        4949.8784, 11981.541 ,  3122.4353, 10191.47  ,  4868.224 ,
        5710.9814, 42495.95  , 44762.07  ,  6227.136 , 10616.408 ,
        4655.2485,  6175.4697,  8073.599 , 41926.902 , 28978.1   ,
        4099.8647, 11262.38  ,  3539.588 , 13955.88  , 45089.26  ,
       12527.653 ,  5046.204 , 10487.552 , 34639.008 , 49195.91  ,
        7134.3145,  2695.999 , 10540.78  , 20997.742 ,  9349.788 ,
       41869.66  , 10932.523 , 14302.973 ,  6469.5654, 10792.44  ,
        6128.6704, 24990.178 , 28355.043 , 47359.223 ,  2262.75  ,
       12493.954 ,  4647.3364,  6799.6294,  9186.158 , 30825.387 ,
       38344.98  , 23967.852 , 13668.629 , 25584.482 ,  6618.285 ,
        2881.889 , 13043.403 , 14349.379 , 11896.118 ,  5546.3174,
       14728.91  , 17411.752 ,  9220.532 ,  1664.677 , 11789.959 ,
        8049.7837, 39275.375 , 10025.217 ,  5791.596 ,  4812.7554,
        9465.37  ,  4115.134 ,  4102.991 , 11613.546 , 10385.475 ,
        7760.079 , 13563.427 , 13333.828 ,  9464.567 ,  5314.1377,
       11200.491 , 15149.408 ,  6611.175 ,  5698.1733,  2202.0596,
        7482.99  ,  6759.925 , 10036.988 ,  3449.6506,  8420.53  ,
       11354.739 ,  5572.967 ,  6959.6704, 27316.646 ,  1680.4277,
       13729.878 ,  7012.1177, 11552.04  ,  4849.694 ,  6407.157 ,
       28602.787 ,  2847.7783,  3689.231 , 14707.184 , 11335.672 ,
       41208.355 ,  7051.6567,  5646.3506, 24742.393 ,  4782.6377,
        3900.4182,  7528.107 ,  6267.7085,  5788.788 ,  5127.899 ,
       12211.355 , 46878.617 , 14895.767 , 19028.576 ,  7469.4897,
       43631.53  ,  5472.921 , 11809.603 ,  7125.292 ,  2287.5557,
       10906.331 , 13999.164 ,  8211.336 ,  4262.0474,  6215.0493,
        4333.8657,  7193.2515,  6614.213 , 15100.086 ,  6918.0977,
        6244.6284,  9387.991 , 10325.574 ,  3632.3687, 12298.279 ,
       15356.606 , 24069.158 , 12157.155 ,  5627.561 ,  2606.3489,
        4524.242 ,  8715.868 , 14320.675 ,  9059.109 ,  4910.365 ,
        7761.57  , 14235.987 , 34712.598 ,  6221.0923, 12701.336 ,
        7943.204 , 38627.36  ,  7815.903 ,  8783.348 ,  9679.163 ,
       11836.8   ,  4989.6963,  9348.784 ,  4395.184 ,  6441.165 ,
       19573.86  , 44459.195 ,  5771.738 ,  4216.9995,  2727.9277,
        1903.7366,  9541.307 ,  2216.6716,  6392.9824,  8051.476 ,
        7445.051 , 24907.545 , 45107.64  , 16839.781 ,  6516.9224,
       10733.315 , 44995.14  ,  9405.623 ], dtype=float32)

In [21]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8898375034332275